global using Furion;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using SimpleAdmin.Core;
global using SimpleRedis;
global using Microsoft.AspNetCore.SignalR;
global using Furion.DependencyInjection;
global using SimpleAdmin.Plugin.Core;