/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    403: typeof import("./src/components/ErrorMessage/403.vue")["default"];
    404: typeof import("./src/components/ErrorMessage/404.vue")["default"];
    500: typeof import("./src/components/ErrorMessage/500.vue")["default"];
    CheckCard: typeof import("./src/components/CheckCard/index.vue")["default"];
    ChooseModule: typeof import("./src/components/ChooseModule/index.vue")["default"];
    CodeHighLight: typeof import("./src/components/CodeHighLight/index.vue")["default"];
    ColSetting: typeof import("./src/components/ProTable/components/ColSetting.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAutocomplete: typeof import("element-plus/es")["ElAutocomplete"];
    ElBadge: typeof import("element-plus/es")["ElBadge"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElColorPicker: typeof import("element-plus/es")["ElColorPicker"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDescriptions: typeof import("element-plus/es")["ElDescriptions"];
    ElDescriptionsItem: typeof import("element-plus/es")["ElDescriptionsItem"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElEmpty: typeof import("element-plus/es")["ElEmpty"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElLink: typeof import("element-plus/es")["ElLink"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElRadioButton: typeof import("element-plus/es")["ElRadioButton"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSlider: typeof import("element-plus/es")["ElSlider"];
    ElSpace: typeof import("element-plus/es")["ElSpace"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    ElTreeSelect: typeof import("element-plus/es")["ElTreeSelect"];
    FormContainer: typeof import("./src/components/FormContainer/index.vue")["default"];
    Grid: typeof import("./src/components/Grid/index.vue")["default"];
    GridItem: typeof import("./src/components/Grid/components/GridItem.vue")["default"];
    Loading: typeof import("./src/components/Loading/index.vue")["default"];
    MenuSelector: typeof import("./src/components/Selectors/MenuSelector/index.vue")["default"];
    Pagination: typeof import("./src/components/ProTable/components/Pagination.vue")["default"];
    ProTable: typeof import("./src/components/ProTable/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SButton: typeof import("./src/components/SButton/index.vue")["default"];
    SearchForm: typeof import("./src/components/SearchForm/index.vue")["default"];
    SearchFormItem: typeof import("./src/components/SearchForm/components/SearchFormItem.vue")["default"];
    SelectIcon: typeof import("./src/components/SelectIcon/index.vue")["default"];
    SelectIconPlus: typeof import("./src/components/SelectIconPlus/index.vue")["default"];
    SvgIcon: typeof import("./src/components/SvgIcon/index.vue")["default"];
    SwitchDark: typeof import("./src/components/SwitchDark/index.vue")["default"];
    TableColumn: typeof import("./src/components/ProTable/components/TableColumn.vue")["default"];
    TreeFilter: typeof import("./src/components/TreeFilter/index.vue")["default"];
  }
}
